# Generated by Django 5.2.8 on 2025-11-26 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonalizado',
            name='username',
            field=models.CharField(error_messages={'unique': 'Um usuário com este nome já existe.'}, help_text='Obrigatório. 150 caracteres ou menos. Letras, dígitos, espaços e @/./+/-/_ apenas.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(flags=0, message='O nome de usuário pode conter letras, números, ESPAÇOS e caracteres @/./+/-/_', regex='^[\\w.@+- ]+$')], verbose_name='username'),
        ),
    ]
