# Generated by Django 5.2.8 on 2025-11-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbeiro', '0001_initial'),
        ('clientes', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id_agendamentos', models.AutoField(primary_key=True, serialize=False)),
                ('data_e_horario_inicio', models.DateTimeField()),
                ('data_e_horario_fim', models.DateTimeField(blank=True, editable=False, null=True)),
                ('fk_barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbeiro.barbeiro')),
                ('fk_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('fk_servicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.servicos')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('fk_barbeiro', 'data_e_horario_inicio'), name='agendamento_unico_por_barbeiro'), models.UniqueConstraint(fields=('fk_cliente', 'data_e_horario_inicio'), name='agendamento_unico_por_cliente')],
            },
        ),
    ]
