# Generated by Django 5.2.8 on 2025-11-22 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id_barbeiro', models.AutoField(primary_key=True, serialize=False)),
                ('foto_barbeiro', models.ImageField(blank=True, null=True, upload_to='fotos_barbeiros/')),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='barber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Excecoes',
            fields=[
                ('id_excecoes', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('motivo_da_indisponibilidade', models.CharField(max_length=200, null=True)),
                ('fk_barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbeiro.barbeiro')),
            ],
        ),
        migrations.CreateModel(
            name='Horarios_de_trabalho',
            fields=[
                ('id_horario_de_trabalho', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.IntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('fk_barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbeiro.barbeiro')),
            ],
        ),
        migrations.AddConstraint(
            model_name='barbeiro',
            constraint=models.UniqueConstraint(fields=('id_barbeiro', 'fk_user'), name='barbeiro_user_unico'),
        ),
        migrations.AddConstraint(
            model_name='excecoes',
            constraint=models.UniqueConstraint(fields=('fk_barbeiro', 'data_inicio'), name='unique_excecao'),
        ),
        migrations.AddConstraint(
            model_name='horarios_de_trabalho',
            constraint=models.UniqueConstraint(fields=('fk_barbeiro', 'dia_semana', 'hora_inicio'), name='unique_horario_barbeiro'),
        ),
    ]
