# Generated by Django 5.2.8 on 2025-11-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios_de_trabalho',
            name='dia_semana',
            field=models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')]),
        ),
    ]
