# Generated by Django 5.2.8 on 2025-11-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiro', '0002_alter_horarios_de_trabalho_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbeiro',
            name='foto_barbeiro',
            field=models.ImageField(default='fotos_barbeiros/sem_foto.jpg', upload_to='fotos_barbeiros/'),
        ),
    ]
