# Generated by Django 5.2.8 on 2025-11-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbeiro', '0003_alter_barbeiro_foto_barbeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbeiro',
            name='foto_barbeiro',
            field=models.ImageField(blank=True, default='fotos_barbeiros/sem_foto.jpg', null=True, upload_to='fotos_barbeiros/'),
        ),
    ]
