# Generated by Django 5.2.8 on 2025-11-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id_servicos', models.AutoField(primary_key=True, serialize=False)),
                ('nome_servico', models.CharField(max_length=100)),
                ('preco_servico', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slot_duracao_servico', models.IntegerField(choices=[(1, '30 minutos'), (2, '1 hora '), (3, '1 hora e 30 minutos')])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('nome_servico', 'preco_servico', 'slot_duracao_servico'), name='servicos_constraint_unicos')],
            },
        ),
    ]
