# Generated by Django 5.2.8 on 2025-11-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servicos_preco_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='nome_servico',
            field=models.CharField(max_length=25),
        ),
    ]
